Repository jellyfin/jellyfin-tizen, pull requests merged in 2024-05, with the labels that each got.

#165 update README
  README.md
Labels: documentation

#250 Add Wiki sync workflow
  .github/workflows/wiki-sync.yml
Labels: ci

#249 Add Wiki sync workflow trigger
  .github/workflows/trigger-wiki-sync.yml
Labels: ci

#254 Add Wiki branch to Renovate
  .github/renovate.json
Labels: dependencies
